import type { Metadata } from "next";
import Link from "next/link";

import { LegalList, LegalPage, LegalSection } from "@/components/legal-page";
import { LEGAL_CONTACT_EMAIL, LEGAL_ENTITY_NAME } from "@/shared/legal";
import { SITE_NAME, buildPageMetadata } from "@/shared/seo";

export const metadata: Metadata = buildPageMetadata({
  title: "Disclaimer - MyStockVision Is Not Investment Advice",
  description:
    "MyStockVision provides stock data and AI-generated analysis for informational purposes only. We are not a SEBI-registered investment adviser or research analyst.",
  path: "/disclaimer",
});

export default function DisclaimerPage() {
  return (
    <LegalPage
      title="Disclaimer"
      intro={`${SITE_NAME} is an informational and educational stock research tool. Nothing on this site is investment advice, and nothing here is a recommendation to buy, sell, or hold any security.`}
    >
      <LegalSection title="We are not a registered adviser">
        <p>
          {LEGAL_ENTITY_NAME} is <strong>not</strong> registered with the Securities and Exchange
          Board of India (SEBI) as an Investment Adviser under the SEBI (Investment Advisers)
          Regulations, 2013, nor as a Research Analyst under the SEBI (Research Analysts)
          Regulations, 2014.
        </p>
        <p>
          Nothing published here should be treated as personalised investment advice. We do not know
          your financial position, risk tolerance, tax situation, or objectives, and no content on
          this site is tailored to them. Before acting on anything you read here, consult a
          SEBI-registered investment adviser.
        </p>
      </LegalSection>

      <LegalSection title="Scores and AI analysis are opinions, not facts">
        <p>
          Features such as Smart Score, AI Risk Analysis, Earnings TLDR, Portfolio Doctor, and
          Competitor Verdict are generated by automated models and statistical heuristics. They are
          interpretations, and they can be wrong.
        </p>
        <LegalList
          items={[
            <>
              AI-generated text can be inaccurate, incomplete, or outdated, and can state incorrect
              claims with apparent confidence.
            </>,
            <>
              Scores are derived from formulas we chose. They are not standardised, not audited, and
              not comparable to any regulated rating.
            </>,
            <>
              A high score is not a buy signal and a low score is not a sell signal.
            </>,
          ]}
        />
      </LegalSection>

      <LegalSection title="Market data may be delayed or wrong">
        <p>
          Prices, fundamentals, corporate actions, and IPO details come from third-party sources
          including NSE, BSE, and external market-data providers. We do not control these sources and
          do not independently verify what they return.
        </p>
        <LegalList
          items={[
            <>Quotes may be delayed and should never be relied on for live trading decisions.</>,
            <>
              Fundamental data may be restated, misclassified, or missing. Figures converted between
              currencies are approximations.
            </>,
            <>
              A provider outage can cause values to be absent or stale without an obvious visual
              indication.
            </>,
          ]}
        />
        <p>
          Always confirm against the company&apos;s own filings and the exchange&apos;s official data
          before acting.
        </p>
      </LegalSection>

      <LegalSection title="Past performance means nothing about the future">
        <p>
          Historical returns, backtests, projections, and CAGR-based estimates shown anywhere on this
          site are hypothetical. They do not predict future results. Investing in securities carries
          risk, including the permanent loss of your capital.
        </p>
      </LegalSection>

      <LegalSection title="Your decisions are your own">
        <p>
          You are solely responsible for your investment decisions and their outcomes. To the fullest
          extent permitted by law, {LEGAL_ENTITY_NAME} accepts no liability for any loss or damage
          arising from reliance on the content of this site. This is expanded on in our{" "}
          <Link href="/terms" className="text-accent underline underline-offset-2">
            Terms of Service
          </Link>
          .
        </p>
        <p>
          Questions about this disclaimer:{" "}
          <a href={`mailto:${LEGAL_CONTACT_EMAIL}`} className="text-accent underline underline-offset-2">
            {LEGAL_CONTACT_EMAIL}
          </a>
        </p>
      </LegalSection>
    </LegalPage>
  );
}
