"use client";

import { cn } from "@/lib/utils";
import { Bot, Sparkles } from "lucide-react";

export function SectionHeading({
  kicker,
  title,
  icon: Icon,
  right,
  className,
}: {
  kicker?: string;
  title: string;
  icon?: React.ElementType;
  right?: React.ReactNode;
  className?: string;
}) {
  return (
    <div className={cn("mb-4 flex items-center justify-between gap-3", className)}>
      <div className="flex items-center gap-3">
        {Icon && (
          <div className="flex h-8 w-8 items-center justify-center rounded-lg border border-border/50 bg-panel/70">
            <Icon className="h-4 w-4 text-brand" />
          </div>
        )}
        <div>
          {kicker && (
            <p className="text-[10px] font-semibold uppercase tracking-[0.22em] text-muted-foreground">{kicker}</p>
          )}
          <h2 className="font-display text-base font-bold tracking-tight text-text sm:text-lg">{title}</h2>
        </div>
      </div>
      {right}
    </div>
  );
}

export function AiSourceBadge({ source }: { source: "ai" | "fallback" }) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider",
        source === "ai"
          ? "border-brand/40 bg-brand/10 text-brand"
          : "border-border/60 bg-panel/70 text-muted-foreground"
      )}
      title={source === "ai" ? "Generated by the AI engine" : "Deterministic local fallback"}
    >
      {source === "ai" ? <Sparkles className="h-3 w-3" /> : <Bot className="h-3 w-3" />}
      {source === "ai" ? "AI" : "Engine"}
    </span>
  );
}

/** Compact inline markdown renderer for AI outputs (bold, headers, bullets). */
export function MarkdownLite({ text, className }: { text: string; className?: string }) {
  const lines = text.split("\n");
  return (
    <div className={cn("space-y-1.5 text-sm leading-6 text-text/90", className)}>
      {lines.map((line, i) => {
        const trimmed = line.trim();
        if (!trimmed) return <div key={i} className="h-1" />;
        if (trimmed.startsWith("### ")) {
          return (
            <h4 key={i} className="pt-1 font-display text-sm font-bold text-text">
              {inline(trimmed.slice(4))}
            </h4>
          );
        }
        if (trimmed.startsWith("## ")) {
          return (
            <h3 key={i} className="pt-2 font-display text-base font-bold text-text">
              {inline(trimmed.slice(3))}
            </h3>
          );
        }
        if (trimmed.startsWith("# ")) {
          return (
            <h2 key={i} className="pt-2 font-display text-lg font-bold text-text">
              {inline(trimmed.slice(2))}
            </h2>
          );
        }
        if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
          return (
            <div key={i} className="flex gap-2 pl-1">
              <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand/80" />
              <p className="flex-1 text-text/90">{inline(trimmed.slice(2))}</p>
            </div>
          );
        }
        if (/^\d+\.\s/.test(trimmed)) {
          const num = trimmed.match(/^(\d+)\./)![1];
          return (
            <div key={i} className="flex gap-2 pl-1">
              <span className="text-xs font-bold text-brand">{num}.</span>
              <p className="flex-1 text-text/90">{inline(trimmed.replace(/^\d+\.\s/, ""))}</p>
            </div>
          );
        }
        return <p key={i}>{inline(trimmed)}</p>;
      })}
    </div>
  );
}

function inline(text: string): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/g);
  return parts.map((part, i) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return (
        <strong key={i} className="font-semibold text-text">
          {part.slice(2, -2)}
        </strong>
      );
    }
    if (part.startsWith("*") && part.endsWith("*") && part.length > 2) {
      return (
        <em key={i} className="italic">
          {part.slice(1, -1)}
        </em>
      );
    }
    if (part.startsWith("`") && part.endsWith("`")) {
      return (
        <code key={i} className="rounded bg-muted px-1 py-0.5 text-xs">
          {part.slice(1, -1)}
        </code>
      );
    }
    return part;
  });
}
