def get_sample_dashboard(symbol: str) -> dict:
    normalized = symbol.upper()
    return {
        "symbol": normalized,
        "companyName": normalized,
        "exchange": "NSE",
        "sector": "",
        "profile": {
            "incorporationYear": 0,
            "headquarters": "",
            "website": "",
            "description": "",
            "chairman": "N/A",
            "previousName": "N/A",
            "industry": "",
        },
        "price": {
            "cmp": 0.0,
            "change": 0.0,
            "changePercent": 0.0,
            "currency": "INR",
            "fiftyTwoWeekLow": 0.0,
            "fiftyTwoWeekHigh": 0.0,
            "history": [],
        },
        "metrics": {
            "marketCap": None,
            "peRatio": None,
            "industryPe": None,
            "pegRatio": None,
            "pbRatio": None,
            "bookValue": None,
            "roe": None,
            "roce": None,
            "roa": None,
            "ebitdaMargin": None,
            "casaRatio": None,
            "netInterestMargin": None,
            "debtToEquity": None,
            "totalDebt": None,
            "dividendYield": None,
            "eps": None,
            "faceValue": None,
            "outstandingShares": None,
            "currentRatio": None,
            "evToSales": None,
            "profitMargin": None,
        },
        "financials": {
            "quarterly": [],
            "quarterlyStandalone": [],
            "quarterlyConsolidated": [],
            "quarterlyDetailedStandalone": [],
            "quarterlyDetailedConsolidated": [],
            "growthSnapshot": {"basis": "consolidated", "periods": []},
            "keyRatioTrends": {"profitability": [], "valuation": [], "liquidity": []},
            "yearly": [],
            "incomeStatement": [],
            "balanceSheet": [],
            "cashFlow": [],
        },
        "corporateActions": {
            "boardMeetings": [],
            "dividends": [],
            "bonusIssues": [],
            "stockSplits": [],
            "rightsIssues": [],
            "agmEgm": [],
            "deals": [],
            "bulkDeals": [],
            "blockDeals": [],
            "insiderTrades": [],
        },
        "documents": {
            "annualReports": [],
            "investorPresentations": [],
            "creditRatings": [],
            "exchangeFilings": [],
        },
        "shareholding": {
            "quarter": "",
            "promoters": 0.0,
            "fii": 0.0,
            "dii": 0.0,
            "public": 0.0,
            "history": [],
            "topHolders": [],
            "sourceUrl": "",
        },
        "brokerageResearch": {
            "source": "Trendlyne",
            "sourceUrl": "",
            "updatedAt": "",
            "summary": {"1D": 0, "1W": 0, "1M": 0, "buy": 0, "hold": 0, "sell": 0, "total": 0},
            "reports": [],
        },
        "news": [],
        "competitors": {
            "table": [],
            "sectorName": "",
            "industryName": "",
            "sectorCompanies": [],
            "industryCompanies": [],
        },
        "technicals": {
            "rsi14": 0.0,
            "macd": 0.0,
            "ema20": 0.0,
            "ema50": 0.0,
            "trend": "Neutral",
            "pivotLevels": {
                "standard": {"s3": 0.0, "s2": 0.0, "s1": 0.0, "pivot": 0.0, "r1": 0.0, "r2": 0.0, "r3": 0.0},
                "fibonacci": {"s3": 0.0, "s2": 0.0, "s1": 0.0, "pivot": 0.0, "r1": 0.0, "r2": 0.0, "r3": 0.0},
            },
        },
    }
