// ─────────────────────────────────────────────────────────────────────────
// Complete A–Z stock directory: NSE + BSE listed companies.
//
// The curated 173-stock UNIVERSE (universe.ts) carries hand-tuned
// fundamentals for large caps. This directory extends coverage with ~325
// additional real listed companies (ticker, name, sector, exchange). Stocks
// outside the curated universe get deterministic synthesized fundamentals
// (see synth.ts), so every directory row is fully browsable: quote, chart,
// scores, financials, news and AI research all work.
//
// Sector labels match the canonical set used by the curated universe.
// ─────────────────────────────────────────────────────────────────────────

export interface DirectoryEntry {
  s: string; // ticker symbol
  n: string; // company name
  sec: string; // canonical sector
  ex: "NSE" | "BSE"; // primary exchange tag for the directory
}

// NSE-listed companies beyond the curated universe. [symbol, name, sector]
const NSE_RAW: [string, string, string][] = [
  // ── A ──
  ["ABCAPITAL", "Aditya Birla Capital", "Financial Services"],
  ["ABFRL", "Aditya Birla Fashion & Retail", "Consumer Cyclical"],
  ["AEGISLOG", "Aegis Logistics", "Energy"],
  ["AIAENG", "AIA Engineering", "Industrials"],
  ["AJANTPHARM", "Ajanta Pharma", "Healthcare"],
  ["AKZOINDIA", "Akzo Nobel India", "Basic Materials"],
  ["ALKYLAMINE", "Alkyl Amines Chemicals", "Basic Materials"],
  ["AMBER", "Amber Enterprises India", "Consumer Cyclical"],
  ["APARINDS", "Apar Industries", "Industrials"],
  ["APLAPOLLO", "APL Apollo Tubes", "Industrials"],
  ["APOLLOMICRO", "Apollo Micro Systems", "Industrials"],
  ["APOLLOTYRE", "Apollo Tyres", "Consumer Cyclical"],
  ["APTUS", "Aptus Value Housing Finance India", "Financial Services"],
  ["ASHOKA", "Ashoka Buildcon", "Industrials"],
  ["ASTRAZEN", "AstraZeneca Pharma India", "Healthcare"],
  ["ATUL", "Atul", "Basic Materials"],
  ["ATULAUTO", "Atul Auto", "Consumer Cyclical"],
  ["AVANTIFEED", "Avanti Feeds", "Consumer Defensive"],
  ["AVADHSUGAR", "Avadh Sugar & Energy", "Consumer Defensive"],
  ["AWL", "Adani Wilmar", "Consumer Defensive"],
  ["ADANIENSOL", "Adani Energy Solutions", "Utilities"],
  ["AFFLE", "Affle 3i", "Technology"],
  ["AARTIIND", "Aarti Industries", "Basic Materials"],
  ["AARTIDRUGS", "Aarti Drugs", "Healthcare"],
  ["ANANTRAJ", "Anant Raj", "Real Estate"],
  // ── B ──
  ["BAJAJELEC", "Bajaj Electricals", "Consumer Cyclical"],
  ["BAJAJHLDNG", "Bajaj Holdings & Investment", "Financial Services"],
  ["BALKRISIND", "Balkrishna Industries", "Consumer Cyclical"],
  ["BANDHANBNK", "Bandhan Bank", "Financial Services"],
  ["BANKINDIA", "Bank of India", "Financial Services"],
  ["BASF", "BASF India", "Basic Materials"],
  ["BATAINDIA", "Bata India", "Consumer Cyclical"],
  ["BAYERCROP", "Bayer CropScience", "Basic Materials"],
  ["BEML", "BEML", "Industrials"],
  ["BHARATRAS", "Bharat Rasayan", "Basic Materials"],
  ["BLUEDART", "Blue Dart Express", "Industrials"],
  ["BODALCHEM", "Bodal Chemicals", "Basic Materials"],
  ["BOMDYEING", "Bombay Dyeing & Manufacturing", "Consumer Cyclical"],
  ["BORORENEW", "Borosil Renewables", "Industrials"],
  ["BOSCHLTD", "Bosch", "Consumer Cyclical"],
  ["BRIGADE", "Brigade Enterprises", "Real Estate"],
  ["BSOFT", "Birlasoft", "Technology"],
  ["BIKAJI", "Bikaji Foods International", "Consumer Defensive"],
  ["BALMLAWRIE", "Balmer Lawrie & Company", "Industrials"],
  ["BLKASHYAP", "B L Kashyap & Sons", "Industrials"],
  // ── C ──
  ["CADILAHC", "Cadila Healthcare", "Healthcare"],
  ["CAMS", "Computer Age Management Services", "Financial Services"],
  ["CANFINHOME", "Can Fin Homes", "Financial Services"],
  ["CAPLIPOINT", "Caplin Point Laboratories", "Healthcare"],
  ["CARBORUNIV", "Carborundum Universal", "Basic Materials"],
  ["CAREERP", "Care Ratings", "Financial Services"],
  ["CARTRADE", "CarTrade Tech", "Consumer Cyclical"],
  ["CASTROLIND", "Castrol India", "Energy"],
  ["CEAT", "CEAT", "Consumer Cyclical"],
  ["CENTURYPLY", "Century Plyboards India", "Consumer Cyclical"],
  ["CENTURYTEX", "Century Textiles & Industries", "Basic Materials"],
  ["CERA", "Cera Sanitaryware", "Consumer Cyclical"],
  ["CESC", "CESC", "Utilities"],
  ["CHAMBLFERT", "Chambal Fertilisers & Chemicals", "Basic Materials"],
  ["CHENNPETRO", "Chennai Petroleum Corporation", "Energy"],
  ["CHOLAHLDNG", "Cholamandalam Financial Holdings", "Financial Services"],
  ["CLEAN", "Clean Science & Technology", "Basic Materials"],
  ["CONCOR", "Container Corporation of India", "Industrials"],
  ["CRISIL", "CRISIL", "Financial Services"],
  ["CSBBANK", "CSB Bank", "Financial Services"],
  ["CUB", "City Union Bank", "Financial Services"],
  ["CUPID", "Cupid", "Healthcare"],
  ["CYIENT", "Cyient", "Technology"],
  // ── D ──
  ["DATAPATTNS", "Data Patterns India", "Technology"],
  ["DCBBANK", "DCB Bank", "Financial Services"],
  ["DCMSHRIRAM", "DCM Shriram", "Basic Materials"],
  ["DEEPAKFERT", "Deepak Fertilisers & Petrochemicals", "Basic Materials"],
  ["DEEPAKNTR", "Deepak Nitrite", "Basic Materials"],
  ["DELHIVERY", "Delhivery", "Industrials"],
  ["DELTACORP", "Delta Corp", "Consumer Cyclical"],
  ["DHANUKA", "Dhanuka Agritech", "Basic Materials"],
  ["DISHTV", "Dish TV India", "Communication Services"],
  ["DLINK", "D-Link India", "Technology"],
  ["DODLA", "Dodla Dairy", "Consumer Defensive"],
  // ── E ──
  ["EASEMYTRIP", "Easy Trip Planners", "Consumer Cyclical"],
  ["EDELWEISS", "Edelweiss Financial Services", "Financial Services"],
  ["EIDPARRY", "EID Parry India", "Consumer Defensive"],
  ["EIHOTELS", "EIH", "Consumer Cyclical"],
  ["ELGIEQUIP", "Elgi Equipments", "Industrials"],
  ["ELECON", "Elecon Engineering Company", "Industrials"],
  ["EMAMILTD", "Emami", "Consumer Defensive"],
  ["EMAMIPAP", "Emami Paper Mills", "Basic Materials"],
  ["ENIL", "Entertainment Network India", "Communication Services"],
  ["ESCORTS", "Escorts Kubota", "Consumer Cyclical"],
  ["EXIDEIND", "Exide Industries", "Consumer Cyclical"],
  // ── F ──
  ["FACT", "Fertilisers & Chemicals Travancore", "Basic Materials"],
  ["FDC", "FDC", "Healthcare"],
  ["FINOLEXCAB", "Finolex Cables", "Industrials"],
  ["FINOLEXIND", "Finolex Industries", "Basic Materials"],
  ["FINEORG", "Fine Organic Industries", "Basic Materials"],
  ["FIVESTAR", "Five Star Business Finance", "Financial Services"],
  ["FLUOROCHEM", "Gujarat Fluorochemicals", "Basic Materials"],
  ["FORCEMOT", "Force Motors", "Consumer Cyclical"],
  ["FSL", "Firstsource Solutions", "Technology"],
  // ── G ──
  ["GHCL", "GHCL", "Basic Materials"],
  ["GICRE", "General Insurance Corporation of India", "Financial Services"],
  ["GILLETTE", "Gillette India", "Consumer Defensive"],
  ["GLAND", "Gland Pharma", "Healthcare"],
  ["GLAXO", "GlaxoSmithKline Pharmaceuticals", "Healthcare"],
  ["GMMPFAUDLR", "GMM Pfaudler", "Industrials"],
  ["GNFC", "Gujarat Narmada Valley Fertilizers & Chemicals", "Basic Materials"],
  ["GODFRYPHLP", "Godfrey Phillips India", "Consumer Defensive"],
  ["GODIGIT", "Go Digit General Insurance", "Financial Services"],
  ["GODREJAGRO", "Godrej Agrovet", "Consumer Defensive"],
  ["GODREJIND", "Godrej Industries", "Consumer Defensive"],
  ["GRAPHITE", "Graphite India", "Industrials"],
  ["GREAVESCOT", "Greaves Cotton", "Industrials"],
  ["GRINDWELL", "Grindwell Norton", "Industrials"],
  ["GRSE", "Garden Reach Shipbuilders & Engineers", "Industrials"],
  ["GESHIP", "Great Eastern Shipping Company", "Industrials"],
  ["GSPL", "Gujarat State Petronet", "Utilities"],
  ["GENUSPOWER", "Genus Power Infrastructures", "Industrials"],
  // ── H ──
  ["HEG", "HEG", "Basic Materials"],
  ["HFCL", "HFCL", "Technology"],
  ["HIMATSEIDE", "Himatsingka Seide", "Consumer Cyclical"],
  ["HINDCOPPER", "Hindustan Copper", "Basic Materials"],
  ["HINDPETRO", "Hindustan Petroleum Corporation", "Energy"],
  ["HONASA", "Honasa Consumer", "Consumer Defensive"],
  ["HONAUT", "Honeywell Automation India", "Industrials"],
  ["HUDCO", "Housing & Urban Development Corporation", "Financial Services"],
  ["HYUNDAI", "Hyundai Motor India", "Consumer Cyclical"],
  // ── I ──
  ["IDBI", "IDBI Bank", "Financial Services"],
  ["IGL", "Indraprastha Gas", "Utilities"],
  ["IIFL", "IIFL Finance", "Financial Services"],
  ["INOXWIND", "Inox Wind", "Utilities"],
  ["INTELLECT", "Intellect Design Arena", "Technology"],
  ["IOB", "Indian Overseas Bank", "Financial Services"],
  ["IRB", "IRB Infrastructure Developers", "Industrials"],
  ["IRCON", "IRCON International", "Industrials"],
  ["IREDA", "Indian Renewable Energy Development Agency", "Financial Services"],
  ["ISGEC", "Isgec Heavy Engineering", "Industrials"],
  ["ISEC", "ICICI Securities", "Financial Services"],
  ["ITI", "ITI", "Technology"],
  ["INGERRAND", "Ingersoll Rand India", "Industrials"],
  // ── J ──
  ["JBCHEPHARM", "JB Chemicals & Pharmaceuticals", "Healthcare"],
  ["JKCEMENT", "JK Cement", "Basic Materials"],
  ["JKLAKSHMI", "JK Lakshmi Cement", "Basic Materials"],
  ["JKTYRE", "JK Tyre & Industries", "Consumer Cyclical"],
  ["JMFINANCIAL", "JM Financial", "Financial Services"],
  ["JINDALSAW", "Jindal SAW", "Industrials"],
  ["JSL", "Jindal Stainless", "Basic Materials"],
  ["JPPOWER", "Jaiprakash Power Ventures", "Utilities"],
  ["JSWENERGY", "JSW Energy", "Utilities"],
  ["JUBLINGREA", "Jubilant Ingrevia", "Basic Materials"],
  ["JUSTDIAL", "Just Dial", "Communication Services"],
  ["JYOTHYLAB", "Jyothy Labs", "Consumer Defensive"],
  // ── K ──
  ["KAYNES", "Kaynes Technology India", "Technology"],
  ["KAVERI", "Kaveri Seed Company", "Consumer Defensive"],
  ["KEI", "KEI Industries", "Industrials"],
  ["KFINTECH", "KFin Technologies", "Financial Services"],
  ["KIMS", "Krishna Institute of Medical Sciences", "Healthcare"],
  ["KPIL", "Kalpataru Projects International", "Industrials"],
  ["KPRMILL", "KPR Mill", "Consumer Cyclical"],
  ["KRBL", "KRBL", "Consumer Defensive"],
  // ── L ──
  ["LALPATHLAB", "Dr Lal PathLabs", "Healthcare"],
  ["LAOPALA", "La Opala RG", "Consumer Cyclical"],
  ["LATENTVIEW", "Latent View Analytics", "Technology"],
  ["LLOYDSME", "Lloyd Metals & Energy", "Basic Materials"],
  ["LUMAXIND", "Lumax Industries", "Consumer Cyclical"],
  ["LUXIND", "Lux Industries", "Consumer Cyclical"],
  ["L&TFH", "L&T Finance", "Financial Services"],
  ["LMW", "Lakshmi Machine Works", "Industrials"],
  // ── M ──
  ["MAHABANK", "Bank of Maharashtra", "Financial Services"],
  ["MAHINDCIE", "Mahindra CIE Automotive", "Consumer Cyclical"],
  ["MAHLOG", "Mahindra Logistics", "Industrials"],
  ["MASFIN", "Mas Financial Services", "Financial Services"],
  ["MASTEK", "Mastek", "Technology"],
  ["MCX", "Multi Commodity Exchange of India", "Financial Services"],
  ["MEDANTA", "Global Health (Medanta)", "Healthcare"],
  ["METROPOLIS", "Metropolis Healthcare", "Healthcare"],
  ["MFSL", "Max Financial Services", "Financial Services"],
  ["MGL", "Mahanagar Gas", "Utilities"],
  ["MHRIL", "Mahindra Holidays & Resorts India", "Consumer Cyclical"],
  ["MOIL", "MOIL", "Basic Materials"],
  ["MOTILALOFS", "Motilal Oswal Financial Services", "Financial Services"],
  ["MAYURUNIQ", "Mayur Uniquoters", "Consumer Cyclical"],
  ["MRPL", "Mangalore Refinery & Petrochemicals", "Energy"],
  ["MRF", "MRF", "Consumer Cyclical"],
  // ── N ──
  ["NAZARA", "Nazara Technologies", "Communication Services"],
  ["NAVINFLUOR", "Navin Fluorine International", "Basic Materials"],
  ["NBCC", "NBCC India", "Real Estate"],
  ["NCC", "NCC", "Industrials"],
  ["NETWORK18", "Network18 Media & Investments", "Communication Services"],
  ["NEULANDLAB", "Neuland Laboratories", "Healthcare"],
  ["NIITLTD", "NIIT", "Technology"],
  ["NLCINDIA", "NLC India", "Utilities"],
  ["NTPCGREEN", "NTPC Green Energy", "Utilities"],
  ["NUVAMA", "Nuvama Wealth Management", "Financial Services"],
  ["NEWGEN", "Newgen Software Technologies", "Technology"],
  // ── O ──
  ["OLAELEC", "Ola Electric Mobility", "Consumer Cyclical"],
  ["ORIENTBELL", "Orient Bell", "Consumer Cyclical"],
  ["ORIENTCEM", "Orient Cement", "Basic Materials"],
  ["ORIENTELEC", "Orient Electric", "Consumer Cyclical"],
  // ── P ──
  ["PEL", "Piramal Enterprises", "Financial Services"],
  ["PFIZER", "Pfizer", "Healthcare"],
  ["PNBHOUSING", "PNB Housing Finance", "Financial Services"],
  ["POLYMED", "Poly Medicure", "Healthcare"],
  ["PRINCEPIPE", "Prince Pipes & Fittings", "Industrials"],
  ["PVRINOX", "PVR INOX", "Communication Services"],
  // ── Q ──
  ["QUESS", "Quess Corp", "Industrials"],
  ["QUICKHEAL", "Quick Heal Technologies", "Technology"],
  // ── R ──
  ["RADICO", "Radico Khaitan", "Consumer Defensive"],
  ["RAILTEL", "RailTel Corporation of India", "Technology"],
  ["RAINBOW", "Rainbow Children's Medicare", "Healthcare"],
  ["RAJESHEXPO", "Rajesh Exports", "Consumer Cyclical"],
  ["RALLIS", "Rallis India", "Basic Materials"],
  ["RAMCOCEM", "The Ramco Cements", "Basic Materials"],
  ["RAMCOSYS", "Ramco Systems", "Technology"],
  ["RAYMOND", "Raymond", "Consumer Cyclical"],
  ["RBLBANK", "RBL Bank", "Financial Services"],
  ["REDINGTON", "Redington", "Technology"],
  ["RELAXO", "Relaxo Footwears", "Consumer Cyclical"],
  ["RITES", "RITES", "Industrials"],
  ["ROSSARI", "Rossari Biotech", "Basic Materials"],
  ["RRKABEL", "RR Kabel", "Industrials"],
  // ── S ──
  ["SANOFI", "Sanofi India", "Healthcare"],
  ["SAREGAMA", "Saregama India", "Communication Services"],
  ["SCHAEFFLER", "Schaeffler India", "Consumer Cyclical"],
  ["SCHNEIDER", "Schneider Electric Infrastructure", "Industrials"],
  ["SEQUENT", "Sequent Scientific", "Healthcare"],
  ["SKFINDIA", "SKF India", "Industrials"],
  ["SOBHA", "Sobha", "Real Estate"],
  ["SONACOMS", "Sona BLW Precision Forgings", "Consumer Cyclical"],
  ["SONATSOFTW", "Sonata Software", "Technology"],
  ["STARHEALTH", "Star Health & Allied Insurance", "Financial Services"],
  ["STLTECH", "Sterling & Wilson Renewable Energy", "Utilities"],
  ["STOVEKRAFT", "Stove Kraft", "Consumer Cyclical"],
  ["STRIDES", "Strides Pharma Science", "Healthcare"],
  ["SUBROS", "Subros", "Consumer Cyclical"],
  ["SUNTV", "Sun TV Network", "Communication Services"],
  ["SUPRAJIT", "Suprajit Engineering", "Consumer Cyclical"],
  ["SUZLON", "Suzlon Energy", "Utilities"],
  ["SWANENG", "Swan Energy", "Consumer Cyclical"],
  // ── T ──
  ["TANLA", "Tanla Platforms", "Technology"],
  ["TATACHEM", "Tata Chemicals", "Basic Materials"],
  ["TATACOMM", "Tata Communications", "Technology"],
  ["TATAINVEST", "Tata Investment Corporation", "Financial Services"],
  ["TATATECH", "Tata Technologies", "Technology"],
  ["TEAMLEASE", "TeamLease Services", "Industrials"],
  ["TCI", "Transport Corporation of India", "Industrials"],
  ["TEJASNET", "Tejas Networks", "Technology"],
  ["THERMAX", "Thermax", "Industrials"],
  ["THYROCARE", "Thyrocare Technologies", "Healthcare"],
  ["TIMKEN", "Timken India", "Industrials"],
  ["TORNTPOWER", "Torrent Power", "Utilities"],
  ["TRIDENT", "Trident", "Consumer Cyclical"],
  ["TVSHOLDING", "TVS Holdings", "Financial Services"],
  ["TVTODAY", "TV Today Network", "Communication Services"],
  // ── U ──
  ["UBL", "United Breweries", "Consumer Defensive"],
  ["UJJIVANSFB", "Ujjivan Small Finance Bank", "Financial Services"],
  ["UNOMINDA", "UNO Minda", "Consumer Cyclical"],
  ["UTIAMC", "UTI Asset Management Company", "Financial Services"],
  // ── V ──
  ["VAKRANGEE", "Vakrangee", "Technology"],
  ["VENKEYS", "Venky's India", "Consumer Defensive"],
  ["VGUARD", "V-Guard Industries", "Consumer Cyclical"],
  ["VINATIORGA", "Vinati Organics", "Basic Materials"],
  ["VIPIND", "VIP Industries", "Consumer Cyclical"],
  ["VMART", "V-Mart Retail", "Consumer Cyclical"],
  // ── W ──
  ["WELCORP", "Welspun Corp", "Industrials"],
  ["WELSPUNLIV", "Welspun Living", "Consumer Cyclical"],
  ["WESTLIFE", "Westlife Foodworld", "Consumer Cyclical"],
  ["WHIRLPOOL", "Whirlpool of India", "Consumer Cyclical"],
  ["WOCKPHARMA", "Wockhardt", "Healthcare"],
  // ── X ──
  ["XPROINDIA", "Xpro India", "Basic Materials"],
  // ── Y ──
  ["YATHARTH", "Yatharth Hospital & Trauma Care Services", "Healthcare"],
  ["YESBANK", "Yes Bank", "Financial Services"],
  // ── Z ──
  ["ZEEL", "Zee Entertainment Enterprises", "Communication Services"],
  ["ZENSARTECH", "Zensar Technologies", "Technology"],
  ["ZENTEC", "Zen Technologies", "Technology"],
  ["ZFCVINDIA", "ZF Commercial Vehicle Control Systems India", "Consumer Cyclical"],
  ["ZOTA", "Zota Health Care", "Healthcare"],
  ["ZYDUSWELL", "Zydus Wellness", "Consumer Defensive"],
  // ── 0-9 ──
  ["3MINDIA", "3M India", "Industrials"],
  ["5PAISA", "5paisa Capital", "Financial Services"],
  ["63MOONS", "63 Moons Technologies", "Technology"],
];

// BSE-listed companies tracked with a BSE-primary tag in the directory.
// Real listed names (many are dual-listed mid/small caps; the BSE tag is the
// browsing lens for this tab). [symbol, name, sector]
const BSE_RAW: [string, string, string][] = [
  // ── A ──
  ["ABSLAMC", "Aditya Birla Sun Life AMC", "Financial Services"],
  ["ADFFOODS", "ADF Foods", "Consumer Defensive"],
  ["ADORWELD", "Ador Welding", "Industrials"],
  ["ALMONDZ", "Almondz Global Securities", "Financial Services"],
  ["AMAL", "Amal", "Basic Materials"],
  ["ARCHIES", "Archies", "Consumer Cyclical"],
  ["ARROWGREEN", "Arrow Greentech", "Basic Materials"],
  ["AURIONPRO", "Aurionpro Solutions", "Technology"],
  // ── B ──
  ["BIRLACORPN", "Birla Corporation", "Basic Materials"],
  ["BLISSGVS", "Bliss GVS Pharma", "Healthcare"],
  ["BOROSIL", "Borosil", "Consumer Cyclical"],
  ["BPL", "BPL", "Consumer Cyclical"],
  // ── C ──
  ["CIGNITI", "Cigniti Technologies", "Technology"],
  ["COSMOFILMS", "Cosmo Films", "Basic Materials"],
  // ── D ──
  ["DALMIASUG", "Dalmia Bharat Sugar & Industries", "Consumer Defensive"],
  ["DATAMATICS", "Datamatics Global Services", "Technology"],
  ["DCW", "DCW", "Basic Materials"],
  ["DHAMPURSUG", "Dhampur Sugar Mills", "Consumer Defensive"],
  ["DOLATALGO", "Dolat Algotech", "Financial Services"],
  // ── F ──
  ["FIEMIND", "FIEM Industries", "Consumer Cyclical"],
  // ── G ──
  ["GABRIEL", "Gabriel India", "Consumer Cyclical"],
  ["GIPCL", "Gujarat Industries Power", "Utilities"],
  ["GPPL", "Gujarat Pipavav Port", "Industrials"],
  ["GRAVITA", "Gravita India", "Basic Materials"],
  ["GTPL", "GTPL Hathway", "Communication Services"],
  ["GUJGASLTD", "Gujarat Gas", "Utilities"],
  // ── H ──
  ["HMT", "HMT", "Industrials"],
  // ── I ──
  ["IFBIND", "IFB Industries", "Consumer Cyclical"],
  ["IFCI", "IFCI", "Financial Services"],
  ["INDIAMART", "IndiaMART InterMESH", "Technology"],
  // ── J ──
  ["JAGRAN", "Jagran Prakashan", "Communication Services"],
  ["JKPAPER", "JK Paper", "Consumer Defensive"],
  // ── K ──
  ["KAJARIA", "Kajaria Ceramics", "Basic Materials"],
  ["KOPRAN", "Kopran", "Healthcare"],
  ["KSB", "KSB", "Industrials"],
  // ── L ──
  ["LGBFORGE", "LGB Forgings", "Consumer Cyclical"],
  // ── M ──
  ["MANINDS", "MAN Industries (India)", "Industrials"],
  ["MARKSANS", "Marksans Pharma", "Healthcare"],
  ["MEGH", "Meghmani Organics", "Basic Materials"],
  ["MERCK", "Merck", "Healthcare"],
  ["MONTECARLO", "Monte Carlo Fashions", "Consumer Cyclical"],
  // ── N ──
  ["NESCO", "Nesco", "Real Estate"],
  ["NILKAMAL", "Nilkamal", "Consumer Cyclical"],
  ["NOCIL", "NOCIL", "Basic Materials"],
  // ── P ──
  ["PENIND", "Pennar Industries", "Industrials"],
  ["PITTIENG", "Pitti Engineering", "Industrials"],
  ["PPAP", "PPAP Automotive", "Consumer Cyclical"],
  ["PTC", "PTC India", "Utilities"],
  // ── R ──
  ["RCF", "Rashtriya Chemicals & Fertilizers", "Basic Materials"],
  ["RELIGARE", "Religare Enterprises", "Financial Services"],
  ["RENUKA", "Shree Renuka Sugars", "Consumer Defensive"],
  // ── S ──
  ["SAFARI", "Safari Industries India", "Consumer Cyclical"],
  ["SASKEN", "Sasken Technologies", "Technology"],
  ["SHILPAMED", "Shilpa Medicare", "Healthcare"],
  ["SKIPPER", "Skipper", "Industrials"],
  ["SMLISUZU", "SML Isuzu", "Consumer Cyclical"],
  ["SPICEJET", "SpiceJet", "Industrials"],
  ["STEELEXG", "Steel Exchange of India", "Basic Materials"],
  ["SUDARSCHEM", "Sudarshan Chemical Industries", "Basic Materials"],
  ["SUNDARMFIN", "Sundaram Finance", "Financial Services"],
  ["SURYAROSNI", "Surya Roshni", "Consumer Cyclical"],
  ["SWARAJENG", "Swaraj Engines", "Industrials"],
  ["SYMPHONY", "Symphony", "Consumer Cyclical"],
  // ── T ──
  ["TRIVENI", "Triveni Engineering & Industries", "Industrials"],
  ["TTKPRESTIG", "TTK Prestige", "Consumer Cyclical"],
  // ── U ──
  ["UCOBANK", "UCO Bank", "Financial Services"],
  ["UFO", "UFO Moviez India", "Technology"],
  ["UNICHEMLAB", "Unichem Laboratories", "Healthcare"],
  // ── V ──
  ["VSTTILLER", "VST Tillers & Tractors", "Consumer Cyclical"],
  // ── W ──
  ["WENDT", "Wendt (India)", "Industrials"],
];

export const RAW_DIRECTORY: DirectoryEntry[] = [
  ...NSE_RAW.map(([s, n, sec]) => ({ s, n, sec, ex: "NSE" as const })),
  ...BSE_RAW.map(([s, n, sec]) => ({ s, n, sec, ex: "BSE" as const })),
];

export const RAW_DIRECTORY_BY_SYMBOL: Record<string, DirectoryEntry> =
  Object.fromEntries(RAW_DIRECTORY.map((e) => [e.s, e]));
